package com.cs3560.web;

import com.cs3560.entity.Choice;
import com.cs3560.entity.Question;
import com.cs3560.service.QuestionInterface;
import com.cs3560.service.StudentInterface;
import com.cs3560.service.VotingServiceImpl;
import java.util.List;
import java.util.Map;

/**
 * Entry of the application
 */

public class SimulationDriver {


    public static void main(String[] args) {
        // Question Interface
        QuestionInterface questionInterface = new VotingServiceImpl();
        // Student Interface
        StudentInterface studentInterface = new VotingServiceImpl();
        // Random generate 5 students.
        studentInterface.randomStudent(5);
        // Create questions
        questionInterface.createQuestions();
        // Get all questions generated by the QuestionInterface
        List<Question> problem = questionInterface.getAllQuestion();
        // Print out all questions
        for (int i =0; i < problem.size(); i++){
            // Get a question from the list
            Question q = problem.get(i);
            // Print the title of the question
            System.out.println(i + 1 + ". " + q.getTitle());
            // Get all choices of the question
            List<Choice> select = q.getChoices();
            // Print out the options
            for (int j = 0; j < select.size(); j++){
                //Get all the option of a question
                Choice option = select.get(j);
                //print out all the option
                System.out.print(option.getChoiceName() + ". " + option.getSingleQuestion());
                //blank line
                System.out.println();

            }
            //blank line
            System.out.println();
            System.out.println("Statistic: ");

            // Each student answer question
            Map<Character, Integer> result = studentInterface.randomAnswerQuestion(q);

            // print the student's choice
            for(Map.Entry<Character, Integer> entry : result.entrySet()){
                System.out.println(entry.getKey() + ": " + entry.getValue());
            }

            //blank line
            System.out.println();

        }




    }

}
